#!/bin/sh
all:
	cd center && make
	cd db && make
	cd game && make
	cd gate && make
	cd hall && make
	cd web && make

clean:
	cd web && make clean
	cd hall && make clean
	cd gate && make clean
	cd game && make clean
	cd db && make clean
	cd center && make clean
	
